
name: MobBountyReloaded
main: org.inesgar.MobBountyReloaded.MobBountyReloaded
version: @VERSION@
authors: [ToppleTheNun, MCForger]
description: Simple plugin that pays and/or fines players for killing mobs.
loadbefore: [MobBountyReloadedExploits, MobBountyReloadedDrops]

permissions:
    mbr.user.collect.normal:
        description: Required for users to be able to collect rewards/fines.
        default: op
    mbr.user.collect.bat:
        description: Allows users to collect rewards/fines for killing bats.
        default: op
    mbr.user.collect.blaze:
        description: Allows users to collect rewards/fines for killing blazes.
        default: op
    mbr.user.collect.cavespider:
        description: Allows users to collect rewards/fines for killing cave spiders.
        default: op
    mbr.user.collect.chicken:
        description: Allows users to collect rewards/fines for killing chickens.
        default: op
    mbr.user.collect.cow:
        description: Allows users to collect rewards/fines for killing cows.
        default: op
    mbr.user.collect.creeper:
        description: Allows users to collect rewards/fines for killing creepers.
        default: op
    mbr.user.collect.electrifiedcreeper:
        description: Allows users to collect rewards/fines for killing electrified creepers.
        default: op
    mbr.user.collect.enderdragon:
        description: Allows users to collect rewards/fines for killing enderdragons.
        default: op
    mbr.user.collect.enderman:
        description: Allows users to collect rewards/fines for killing endermen.
        default: op
    mbr.user.collect.ghast:
        description: Allows users to collect rewards/fines for killing ghast.
        default: op
    mbr.user.collect.giant:
        description: Allows users to collect rewards/fines for killing giants.
        default: op
    mbr.user.collect.irongolem:
        description: Allows users to collect rewards/fines for killing iron golems.
        default: op
    mbr.user.collect.magmacube:
        description: Allows users to collect rewards/fines for killing magma cubes.
        default: op
    mbr.user.collect.monster:
        description: Allows users to collect rewards/fines for killing monsters.
        default: op
    mbr.user.collect.mooshroom:
        description: Allows users to collect rewards/fines for killing mooshrooms.
        default: op
    mbr.user.collect.ocelot:
        description: Allows users to collect rewards/fines for killing ocelots.
        default: op
    mbr.user.collect.pig:
        description: Allows users to collect rewards/fines for killing pigs.
        default: op
    mbr.user.collect.pigzombie:
        description: Allows users to collect rewards/fines for killing pig zombies.
        default: op
    mbr.user.collect.player:
        description: Allows users to collect rewards/fines for killing players.
        default: op
    mbr.user.collect.selftamedcat:
        description: Allows users to collect rewards/fines for killing self tamed cats.
        default: op
    mbr.user.collect.selftamedwolf:
        description: Allows users to collect rewards/fines for killing self tamed wolves.
        default: op
    mbr.user.collect.sheep:
        description: Allows users to collect rewards/fines for killing sheep.
        default: op
    mbr.user.collect.silverfish:
        description: Allows users to collect rewards/fines for killing silverfish.
        default: op
    mbr.user.collect.skeleton:
        description: Allows users to collect rewards/fines for killing skeletons.
        default: op
    mbr.user.collect.slime:
        description: Allows users to collect rewards/fines for killing slimes.
        default: op
    mbr.user.collect.snowgolem:
        description: Allows users to collect rewards/fines for killing snow golems.
        default: op
    mbr.user.collect.spider:
        description: Allows users to collect rewards/fines for killing spiders.
        default: op
    mbr.user.collect.squid:
        description: Allows users to collect rewards/fines for killing squids.
        default: op
    mbr.user.collect.tamedcat:
        description: Allows users to collect rewards/fines for killing tamed cats.
        default: op
    mbr.user.collect.tamedwolf:
        description: Allows users to collect rewards/fines for killing tamed wolves.
        default: op
    mbr.user.collect.unknown:
        description: Allows users to collect rewards/fines for killing unknown creatures.
        default: op
    mbr.user.collect.villager:
        description: Allows users to collect rewards/fines for killing villagers.
        default: op
    mbr.user.collect.witch:
        description: Allows users to collect rewards/fines for killing witches.
        default: op
    mbr.user.collect.wither:
        description: Allows users to collect rewards/fines for killing withers.
        default: op
    mbr.user.collect.witherskeleton:
        description: Allows users to collect rewards/fines for killing wither skeletons.
        default: op
    mbr.user.collect.wolf:
        description: Allows users to collect rewards/fines for killing wolves.
        default: op
    mbr.user.collect.zombie:
        description: Allows users to collect rewards/fines for killing zombies.
        default: op
    mbr.user.collect.*:
        description: Gives users all collection permissions.
        default: op
        children:
            mbr.user.collect.normal: true
            mbr.user.collect.bat: true
            mbr.user.collect.blaze: true
            mbr.user.collect.cavespider: true
            mbr.user.collect.chicken: true
            mbr.user.collect.cow: true
            mbr.user.collect.creeper: true
            mbr.user.collect.electrifiedcreeper: true
            mbr.user.collect.enderdragon: true
            mbr.user.collect.enderman: true
            mbr.user.collect.ghast: true
            mbr.user.collect.giant: true
            mbr.user.collect.irongolem: true
            mbr.user.collect.magmacube: true
            mbr.user.collect.monster: true
            mbr.user.collect.mooshroom: true
            mbr.user.collect.ocelot: true
            mbr.user.collect.pig: true
            mbr.user.collect.pigzombie: true
            mbr.user.collect.player: true
            mbr.user.collect.selftamedcat: true
            mbr.user.collect.selftamedwolf: true
            mbr.user.collect.sheep: true
            mbr.user.collect.silverfish: true
            mbr.user.collect.skeleton: true
            mbr.user.collect.slime: true
            mbr.user.collect.snowgolem: true
            mbr.user.collect.spider: true
            mbr.user.collect.squid: true
            mbr.user.collect.tamedcat: true
            mbr.user.collect.tamedwolf: true
            mbr.user.collect.unknown: true
            mbr.user.collect.villager: true
            mbr.user.collect.witch: true
            mbr.user.collect.wither: true
            mbr.user.collect.witherskeleton: true
            mbr.user.collect.wolf: true
            mbr.user.collect.zombie: true
    mbr.user.command.check:
        description: Allows user to check value of creatures.
        default: op
    mbr.user.finebypass:
        description: Allows user to bypass fines.
        default: false
    mbr.user.*:
        description: Gives all user permissions.
        default: op
        children:
            mbr.user.collect.normal: true
            mbr.user.collect.bat: true
            mbr.user.collect.blaze: true
            mbr.user.collect.cavespider: true
            mbr.user.collect.chicken: true
            mbr.user.collect.cow: true
            mbr.user.collect.creeper: true
            mbr.user.collect.electrifiedcreeper: true
            mbr.user.collect.enderdragon: true
            mbr.user.collect.enderman: true
            mbr.user.collect.ghast: true
            mbr.user.collect.giant: true
            mbr.user.collect.irongolem: true
            mbr.user.collect.magmacube: true
            mbr.user.collect.monster: true
            mbr.user.collect.mooshroom: true
            mbr.user.collect.ocelot: true
            mbr.user.collect.pig: true
            mbr.user.collect.pigzombie: true
            mbr.user.collect.player: true
            mbr.user.collect.selftamedcat: true
            mbr.user.collect.selftamedwolf: true
            mbr.user.collect.sheep: true
            mbr.user.collect.silverfish: true
            mbr.user.collect.skeleton: true
            mbr.user.collect.slime: true
            mbr.user.collect.snowgolem: true
            mbr.user.collect.spider: true
            mbr.user.collect.squid: true
            mbr.user.collect.tamedcat: true
            mbr.user.collect.tamedwolf: true
            mbr.user.collect.unknown: true
            mbr.user.collect.villager: true
            mbr.user.collect.witch: true
            mbr.user.collect.wither: true
            mbr.user.collect.witherskeleton: true
            mbr.user.collect.wolf: true
            mbr.user.collect.zombie: true
            mbr.user.command.check: true
    mbr.admin.command.load:
        description: Allows user to reload configs.
        default: op
    mbr.admin.command.save:
        description: Allows user to save configs.
        default: op
    mbr.admin.command.reward:
        description: Allows user to change mob value.
        default: op
    mbr.admin.command.worldreward:
        description: Allows user to change mob value per world.
        default: op
    mbr.admin.command.mbgm:
        description: Allows user to change group multipliers.
        default: op       
    mbr.admin.command.mbum:
        description: Allows user to change user multipliers.
        default: op
    mbr.admin.command.mbem:
        description: Allows user to change environment multipliers.
        default: op
    mbr.admin.command.mbtm:
        description: Allows user to change time multipliers.
        default: op
    mbr.admin.command.mbg:
        description: Allows user to change general settings.
        default: op
    mbr.admin.debug:
        description: Allows user to receive debug messages.
        default: op
    mbr.admin.command.*:
        description: Gives all user permissions.
        default: op
        children:
            mbr.admin.command.load: true
            mbr.admin.command.save: true
            mbr.admin.command.reward: true
            mbr.admin.command.worldreward: true
            mbr.admin.command.mbgm: true
            mbr.admin.command.mbum: true
            mbr.admin.command.mbem: true
            mbr.admin.command.mbtm: true
            mbr.admin.command.mbg: true
    mbr.admin.*:
        description: Gives all user permissions.
        default: op
        children:
            mbr.admin.command.load: true
            mbr.admin.command.save: true
            mbr.admin.command.reward: true
            mbr.admin.command.worldreward: true
            mbr.admin.command.mbgm: true
            mbr.admin.command.mbum: true
            mbr.admin.command.mbem: true
            mbr.admin.command.mbtm: true
            mbr.admin.command.mbg: true
            mbr.admin.debug: true
    mbr.*:
        description: Gives all user permissions.
        default: op
        children:
            mbr.user.collect.normal: true
            mbr.user.collect.bat: true
            mbr.user.collect.blaze: true
            mbr.user.collect.cavespider: true
            mbr.user.collect.chicken: true
            mbr.user.collect.cow: true
            mbr.user.collect.creeper: true
            mbr.user.collect.electrifiedcreeper: true
            mbr.user.collect.enderdragon: true
            mbr.user.collect.enderman: true
            mbr.user.collect.ghast: true
            mbr.user.collect.giant: true
            mbr.user.collect.irongolem: true
            mbr.user.collect.magmacube: true
            mbr.user.collect.monster: true
            mbr.user.collect.mooshroom: true
            mbr.user.collect.ocelot: true
            mbr.user.collect.pig: true
            mbr.user.collect.pigzombie: true
            mbr.user.collect.player: true
            mbr.user.collect.selftamedcat: true
            mbr.user.collect.selftamedwolf: true
            mbr.user.collect.sheep: true
            mbr.user.collect.silverfish: true
            mbr.user.collect.skeleton: true
            mbr.user.collect.slime: true
            mbr.user.collect.snowgolem: true
            mbr.user.collect.spider: true
            mbr.user.collect.squid: true
            mbr.user.collect.tamedcat: true
            mbr.user.collect.tamedwolf: true
            mbr.user.collect.unknown: true
            mbr.user.collect.villager: true
            mbr.user.collect.witch: true
            mbr.user.collect.wither: true
            mbr.user.collect.witherskeleton: true
            mbr.user.collect.wolf: true
            mbr.user.collect.zombie: true
            mbr.user.command.check: true
            mbr.admin.command.load: true
            mbr.admin.command.save: true
            mbr.admin.command.reward: true
            mbr.admin.command.worldreward: true
            mbr.admin.command.mbgm: true
            mbr.admin.command.mbum: true
            mbr.admin.command.mbem: true
            mbr.admin.command.mbtm: true
            mbr.admin.command.mbg: true
            mbr.admin.debug: true
commands:
    mobbountyload:
        description: Allows user to reload the MBR configs.
        aliases: [mbload,mbl,mobbountyl,mbountyload,mbountyl,mobbl,mobbload]
        usage: /<command>
    mobbountysave:
        description: Allows user to reload the MBR configs.
        aliases: [mbsave,mbs,mobbountys,mbountysave,mbountys,mobbs,mobbsave]
        usage: /<command>
    mobbountycheck:
        description: Allows user to check the values for creatures.
        aliases: [mbcheck,mbc,mobbountyc,mbountycheck,mbountyc,mobbc,mobbcheck]
        usage: /<command>
    mobbounty:
        description: Allows user to see MobBountyReloaded information.
        aliases: [mb, mbounty, mobb]
        usage: /<command>
    mobbountyreward:
        description: Allows user to change values of creatures.
        aliases: [mbreward, mbr, mobbountyr,mbountyreward,mbountyr,mobbr,mobbreward]
        usage: /<command> <creature> <value>
    mobbountyworldreward:
        description: Allows user to change values of creatures per world.
        aliases: [mbwreward, mbwr, mobbountywr, mbountywreward, mbountyworldreward,mbountywr,mobbwr,mobbwreward]
        usage: /<command> <world> <creature> [amount]
    mobbountygroupmulti:
        description: Allows user to change a group multiplier.
        aliases: [mbgmulti, mbgm, mobbountygm, mbountygmulti, mbountygroupmulti,mbountygm,mobbgm,mobbgmulti]
        usage: /<command> <group> <amount>
    mobbountyusermulti:
        description: Allows user to change a user multiplier.
        aliases: [mbumulti, mbum, mobbountyum, mbountyumulti, mbountyusermulti,mbountyum,mobbum,mobbumulti]
        usage: /<command> <user> <amount>
    mobbountyenvmulti:
        description: Allows user to change an environment multiplier.
        aliases: [mbemulti, mbem, mobbountyem, mbountyemulti, mbountyemulti,mbountyem,mobbem,mobbemulti]
        usage: /<command> <environment> <amount>
    mobbountytimemulti:
        description: Allows user to change a time multiplier.
        aliases: [mbtmulti, mbtm, mobbountytm, mbountytmulti, mbountytmulti,mbountytm,mobbem,mobbtmulti]
        usage: /<command> <time> <amount>
    mobbountygeneral:
        description: Allows user to change values of creatures.
        aliases: [mbgeneral, mbg, mobbountyg,mbountygeneral,mbountyg,mobbg,mobbgeneral]
        usage: /<command> <creature> <value>